# https://alacritty.org/config-alacritty.html

import = ["~/.config/alacritty/themes/themes/gruvbox_dark.toml"]

[font]
size = 18

[font.normal]
family = "Fira Code"

[window]
decorations = "none"

[window.padding]
x = 7
y = 7

[keyboard]
bindings = [
  # { key = "C", mods = "Control", action = "Copy" },
  { key = "V", mods = "Control", action = "Paste" },
]
